# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160109_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
    ]
