# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Project'),
        ),
    ]
