# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20160109_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('pl', 'Programming Language'), ('st', 'Software Tools'), ('fr', 'Frameworks'), ('ps', 'Professional Skills')], default='pl', max_length=2),
            preserve_default=False,
        ),
    ]
