# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 17:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20160109_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency_level',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
