# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20161114_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='employer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='employers'),
        ),
    ]
